# Generated by Django 4.1.4 on 2022-12-25 21:51

from django.db import migrations, models
import imageUpload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.ImageField(upload_to=imageUpload.models.Image)),
                ("prediction_text", models.TextField(blank=True, null=True)),
                (
                    "prediction_percentage",
                    models.TextField(blank=True, max_length=10, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
